/* General JS utility for Flask HealthTwin app */

const HEALTH_TWIN_TRANSLATIONS = {
    en: {
        'language.label': 'Language',
        'theme.dark': 'Dark',
        'theme.light': 'Light',
        'nav.home': 'Home',
        'nav.dashboard': '📊 Dashboard',
        'nav.history': '📈 History',
        'nav.records': '🧾 Records',
        'nav.diabetes': '🩸 Diabetes',
        'nav.heart': '❤️ Heart',
        'nav.brain': '🧠 Brain Tumor',
        'nav.watch': '⌚ Watch',
        'nav.chat': '💬 AI Chat',
        'auth.login': 'Login',
        'auth.register': 'Register',
        'auth.logout': 'Logout',
        'auth.tagline': 'Your Digital Health Twin',
        'footer.disclaimer': '⚕️ HealthTwin v2.0 - AI-powered health predictions are for educational purposes only. Always consult a medical professional.',
        'home.badge': 'Precision health intelligence',
        'home.title': 'Meet the AI layer for your health twin.',
        'home.subtitle': 'HealthTwin brings prediction tools, daily vitals tracking, and an always-on medical assistant into one calm workspace designed to help you notice risk earlier and act with confidence.',
        'home.open_dashboard': 'Open dashboard',
        'home.talk_ai': 'Talk to AI',
        'home.review_history': 'Review history',
        'home.create_account': 'Create free account',
        'home.sign_in': 'Sign in',
        'home.stat_models_title': '3 core models',
        'home.stat_models_copy': 'Diabetes, heart, and MRI support',
        'home.stat_cockpit_title': '1 unified cockpit',
        'home.stat_cockpit_copy': 'Predictions, watch data, and history',
        'home.stat_ai_title': '24/7 AI guidance',
        'home.stat_ai_copy': 'Questions, explanations, and next steps',
        'home.snapshot_kicker': 'Live wellness snapshot',
        'home.health_score_small': 'health score',
        'home.recovery_trend': 'Recovery trend',
        'home.recovery_value': 'Stable',
        'home.sleep_consistency': 'Sleep consistency',
        'home.heart_load': 'Heart load',
        'home.heart_load_value': 'Watch closely',
        'home.covers_kicker': 'What HealthTwin covers',
        'home.cover_predictions_title': 'Predictions',
        'home.cover_predictions_copy': 'ML support for key disease risk checks',
        'home.cover_assistant_title': 'Assistant',
        'home.cover_assistant_copy': 'Medical Q&A with retrieval-backed answers',
        'home.cover_tracking_title': 'Tracking',
        'home.cover_tracking_copy': 'Vitals, logs, charts, and wearable simulation',
        'home.cover_history_title': 'History',
        'home.cover_history_copy': 'See trends and identify changes over time',
        'home.stat_pipeline': 'Disease prediction pipelines',
        'home.stat_assistant': 'Medical assistant with contextual retrieval',
        'home.stat_view': 'View of logs, vitals, and simulated wearables',
        'home.stat_fast': 'Analyze, save, and revisit your health snapshots',
        'home.modules_kicker': 'Platform modules',
        'home.modules_title': 'Everything important, one screen away.',
        'home.modules_copy': 'Each tool is designed around practical health workflows: measure, assess, understand, and monitor.',
        'home.card_dashboard_title': 'Health Dashboard',
        'home.card_dashboard_copy': 'Calculate your health score, track key vitals, surface risk indicators, and ask for AI advice in the same workflow.',
        'home.card_history_title': 'Health History',
        'home.card_history_copy': 'Review saved logs over time with charts that reveal patterns in recovery, habits, and consistency.',
        'home.card_diabetes_title': 'Diabetes Risk',
        'home.card_diabetes_copy': 'Estimate diabetes likelihood from core biometric inputs like glucose, BMI, age, and related factors.',
        'home.card_heart_title': 'Heart Disease Detection',
        'home.card_heart_copy': 'Evaluate cardiovascular risk through blood pressure, cholesterol, ECG-linked signals, and other vitals.',
        'home.card_brain_title': 'Brain MRI Classifier',
        'home.card_brain_copy': 'Use image-based deep learning support to classify MRI scans across major brain tumor categories.',
        'home.card_watch_title': 'Smart Watch Simulation',
        'home.card_watch_copy': 'Explore heart rate, oxygen, stress, and activity streams through a companion wearable-style dashboard.',
        'home.card_ai_title': 'AI Medical Assistant',
        'home.card_ai_copy': 'Ask symptoms, treatment, recovery, and wellness questions in a focused interface built for guidance and clarity.',
        'login.title': 'Welcome Back',
        'login.subtitle': 'Sign in to access your health dashboard',
        'login.remember': 'Remember me',
        'login.submit': 'Sign In →',
        'login.switch_prefix': "Don't have an account?",
        'login.switch_link': 'Create one',
        'register.title': 'Create Account',
        'register.subtitle': 'Start tracking your health journey',
        'register.confirm_password': 'Confirm Password',
        'register.submit': 'Create Account →',
        'register.switch_prefix': 'Already have an account?',
        'register.switch_link': 'Sign in',
        'form.username': 'Username',
        'form.email': 'Email',
        'form.password': 'Password',
        'form.gender': 'Gender',
        'form.age': 'Age',
        'form.weight': 'Weight (kg)',
        'form.height': 'Height (cm)',
        'form.steps': 'Daily Steps',
        'form.sleep': 'Sleep (hours)',
        'form.water': 'Water (litres)',
        'form.heart_rate': 'Heart Rate (bpm)',
        'placeholder.username': 'Enter your username',
        'placeholder.choose_username': 'Choose a username',
        'placeholder.password': 'Enter your password',
        'placeholder.password_min': 'Min. 6 characters',
        'placeholder.repeat_password': 'Repeat password',
        'placeholder.email': 'your@email.com',
        'dashboard.title': '📊 Health Dashboard',
        'dashboard.welcome': 'Welcome back,',
        'dashboard.health_score': 'Health Score',
        'dashboard.out_of_100': 'out of 100',
        'dashboard.vitals': '👤 Your Vitals',
        'dashboard.analyze': '🔍 Analyze',
        'dashboard.save_log': '💾 Save Log',
        'dashboard.placeholder': 'Enter your vitals and click Analyze to see your health metrics',
        'dashboard.breakdown': 'Health Score Breakdown',
        'dashboard.overall_score': 'Overall Score',
        'dashboard.risk_summary': 'Risk Summary',
        'dashboard.ai_advisor': '🤖 AI Health Advisor',
        'dashboard.quick_tired': 'Why am I tired?',
        'dashboard.quick_improve': 'Improve my score',
        'dashboard.quick_weight': 'Weight status',
        'dashboard.quick_tips': 'Health tips',
        'dashboard.ask_health_question': 'Ask a health question...',
        'dashboard.history_header': '📈 Health History',
        'records.vault': '🧾 Medical Records Vault',
        'records.add_title': 'Add Bills & Prescriptions',
        'records.add_copy': 'Upload hospital bills or doctor prescriptions so they stay attached to your account for future access.',
        'records.document_type': 'Document Type',
        'records.bill': 'Bill',
        'records.prescription': 'Prescription',
        'records.title': 'Title',
        'records.notes': 'Notes',
        'records.file': 'File',
        'records.save_document': 'Save Document',
        'records.saved_documents': 'Saved Documents',
        'records.saved_copy': 'Recent bills and prescriptions stored in your account.',
        'records.view_all': 'View All',
        'records.download': 'Download',
        'records.empty': 'No stored records yet. Upload your first bill or prescription to keep it for future visits.',
        'records.saved_bills': '🧾 Saved Bills & Prescriptions',
        'records.page_title': '🧾 Medical Records',
        'records.page_subtitle': 'Bills and doctor prescriptions stored securely for your future visits.',
        'records.page_empty': 'No documents saved yet. Use the dashboard upload section to add bills and prescriptions for future reference.',
        'records.ocr_preview': 'OCR Preview',
        'records.empty_history_prefix': 'No saved bills or prescriptions yet. Upload them from your',
        'records.empty_history_link': 'dashboard',
        'records.title_placeholder': 'Apollo bill - March 2026',
        'records.notes_placeholder': 'Doctor name, visit reason, amount paid, or any reminder',
        'history.title': '📈 Health History',
        'history.subtitle_prefix': 'Your complete wellness journey',
        'history.subtitle_suffix': 'total records',
        'history.back': '← Back to Dashboard',
        'history.statistics': '📊 Statistics Summary',
        'history.all_records': '📋 All Records',
        'history.empty_prefix': 'No health history yet.',
        'history.empty_link': 'Go to the Dashboard',
        'history.empty_suffix': 'to save your first log.'
    },
    hi: {
        'language.label': 'भाषा',
        'theme.dark': 'डार्क',
        'theme.light': 'लाइट',
        'nav.home': 'होम',
        'nav.dashboard': '📊 डैशबोर्ड',
        'nav.history': '📈 हिस्ट्री',
        'nav.records': '🧾 रिकॉर्ड्स',
        'nav.diabetes': '🩸 डायबिटीज',
        'nav.heart': '❤️ हार्ट',
        'nav.brain': '🧠 ब्रेन ट्यूमर',
        'nav.watch': '⌚ वॉच',
        'nav.chat': '💬 एआई चैट',
        'auth.login': 'लॉगिन',
        'auth.register': 'रजिस्टर',
        'auth.logout': 'लॉगआउट',
        'auth.tagline': 'आपका डिजिटल हेल्थ ट्विन',
        'footer.disclaimer': '⚕️ HealthTwin v2.0 - एआई आधारित स्वास्थ्य भविष्यवाणियां केवल शैक्षणिक उपयोग के लिए हैं। हमेशा डॉक्टर से सलाह लें।',
        'home.badge': 'प्रिसिशन हेल्थ इंटेलिजेंस',
        'home.title': 'अपने हेल्थ ट्विन के लिए एआई लेयर से मिलिए।',
        'home.subtitle': 'HealthTwin भविष्यवाणी टूल्स, दैनिक वाइटल ट्रैकिंग, और हमेशा उपलब्ध मेडिकल असिस्टेंट को एक शांत कार्यक्षेत्र में लाता है ताकि आप जोखिम को जल्दी पहचान सकें और आत्मविश्वास से कदम उठा सकें।',
        'home.open_dashboard': 'डैशबोर्ड खोलें',
        'home.talk_ai': 'एआई से बात करें',
        'home.review_history': 'हिस्ट्री देखें',
        'home.create_account': 'मुफ्त अकाउंट बनाएं',
        'home.sign_in': 'साइन इन',
        'home.stat_models_title': '3 मुख्य मॉडल',
        'home.stat_models_copy': 'डायबिटीज, हार्ट, और एमआरआई सहायता',
        'home.stat_cockpit_title': '1 एकीकृत कॉकपिट',
        'home.stat_cockpit_copy': 'प्रीडिक्शन, वॉच डेटा, और हिस्ट्री',
        'home.stat_ai_title': '24/7 एआई मार्गदर्शन',
        'home.stat_ai_copy': 'सवाल, व्याख्या, और अगले कदम',
        'home.snapshot_kicker': 'लाइव वेलनेस स्नैपशॉट',
        'home.health_score_small': 'हेल्थ स्कोर',
        'home.recovery_trend': 'रिकवरी ट्रेंड',
        'home.recovery_value': 'स्थिर',
        'home.sleep_consistency': 'नींद की निरंतरता',
        'home.heart_load': 'हार्ट लोड',
        'home.heart_load_value': 'नज़र रखें',
        'home.covers_kicker': 'HealthTwin क्या कवर करता है',
        'home.cover_predictions_title': 'प्रीडिक्शन्स',
        'home.cover_predictions_copy': 'मुख्य रोग जोखिम जांच के लिए एमएल सहायता',
        'home.cover_assistant_title': 'असिस्टेंट',
        'home.cover_assistant_copy': 'रिट्रीवल-समर्थित उत्तरों के साथ मेडिकल प्रश्नोत्तर',
        'home.cover_tracking_title': 'ट्रैकिंग',
        'home.cover_tracking_copy': 'वाइटल्स, लॉग्स, चार्ट्स और वियरेबल सिमुलेशन',
        'home.cover_history_title': 'हिस्ट्री',
        'home.cover_history_copy': 'समय के साथ रुझान देखें और बदलाव पहचानें',
        'home.stat_pipeline': 'रोग भविष्यवाणी पाइपलाइनें',
        'home.stat_assistant': 'संदर्भित जानकारी वाला मेडिकल असिस्टेंट',
        'home.stat_view': 'लॉग्स, वाइटल्स और सिम्युलेटेड वियरेबल्स का दृश्य',
        'home.stat_fast': 'विश्लेषण करें, सेव करें और अपने हेल्थ स्नैपशॉट फिर देखें',
        'home.modules_kicker': 'प्लेटफ़ॉर्म मॉड्यूल्स',
        'home.modules_title': 'हर महत्वपूर्ण चीज़, बस एक स्क्रीन दूर।',
        'home.modules_copy': 'हर टूल व्यावहारिक स्वास्थ्य वर्कफ़्लो के लिए बनाया गया है: मापें, आकलन करें, समझें और मॉनिटर करें।',
        'home.card_dashboard_title': 'हेल्थ डैशबोर्ड',
        'home.card_dashboard_copy': 'अपना हेल्थ स्कोर निकालें, मुख्य वाइटल्स ट्रैक करें, जोखिम संकेत देखें और उसी वर्कफ़्लो में एआई सलाह लें।',
        'home.card_history_title': 'हेल्थ हिस्ट्री',
        'home.card_history_copy': 'समय के साथ सेव किए गए लॉग्स को चार्ट्स में देखें जो रिकवरी, आदतों और स्थिरता के पैटर्न दिखाते हैं।',
        'home.card_diabetes_title': 'डायबिटीज जोखिम',
        'home.card_diabetes_copy': 'ग्लूकोज़, बीएमआई, उम्र और अन्य कारकों जैसे बायोमेट्रिक इनपुट्स से डायबिटीज की संभावना का अनुमान लगाएं।',
        'home.card_heart_title': 'हार्ट डिजीज डिटेक्शन',
        'home.card_heart_copy': 'ब्लड प्रेशर, कोलेस्ट्रॉल, ईसीजी संबंधित संकेतों और अन्य वाइटल्स के आधार पर कार्डियोवैस्कुलर जोखिम का मूल्यांकन करें।',
        'home.card_brain_title': 'ब्रेन एमआरआई क्लासिफ़ायर',
        'home.card_brain_copy': 'इमेज-आधारित डीप लर्निंग सहायता से एमआरआई स्कैन को प्रमुख ब्रेन ट्यूमर श्रेणियों में वर्गीकृत करें।',
        'home.card_watch_title': 'स्मार्ट वॉच सिमुलेशन',
        'home.card_watch_copy': 'कंपैनियन वियरेबल-स्टाइल डैशबोर्ड के माध्यम से हार्ट रेट, ऑक्सीजन, स्ट्रेस और एक्टिविटी स्ट्रीम्स देखें।',
        'home.card_ai_title': 'एआई मेडिकल असिस्टेंट',
        'home.card_ai_copy': 'मार्गदर्शन और स्पष्टता के लिए बने केंद्रित इंटरफ़ेस में लक्षण, उपचार, रिकवरी और वेलनेस सवाल पूछें।',
        'login.title': 'वापसी पर स्वागत है',
        'login.subtitle': 'अपना हेल्थ डैशबोर्ड देखने के लिए साइन इन करें',
        'login.remember': 'मुझे याद रखें',
        'login.submit': 'साइन इन →',
        'login.switch_prefix': 'क्या आपका अकाउंट नहीं है?',
        'login.switch_link': 'एक बनाएं',
        'register.title': 'अकाउंट बनाएं',
        'register.subtitle': 'अपनी हेल्थ यात्रा ट्रैक करना शुरू करें',
        'register.confirm_password': 'पासवर्ड की पुष्टि करें',
        'register.submit': 'अकाउंट बनाएं →',
        'register.switch_prefix': 'क्या आपका अकाउंट पहले से है?',
        'register.switch_link': 'साइन इन',
        'form.username': 'यूज़रनेम',
        'form.email': 'ईमेल',
        'form.password': 'पासवर्ड',
        'form.gender': 'लिंग',
        'form.age': 'उम्र',
        'form.weight': 'वज़न (किलो)',
        'form.height': 'ऊंचाई (सेमी)',
        'form.steps': 'दैनिक कदम',
        'form.sleep': 'नींद (घंटे)',
        'form.water': 'पानी (लीटर)',
        'form.heart_rate': 'हार्ट रेट (बीपीएम)',
        'placeholder.username': 'अपना यूज़रनेम दर्ज करें',
        'placeholder.choose_username': 'यूज़रनेम चुनें',
        'placeholder.password': 'अपना पासवर्ड दर्ज करें',
        'placeholder.password_min': 'कम से कम 6 अक्षर',
        'placeholder.repeat_password': 'पासवर्ड दोबारा दर्ज करें',
        'placeholder.email': 'your@email.com',
        'dashboard.title': '📊 हेल्थ डैशबोर्ड',
        'dashboard.welcome': 'फिर से स्वागत है,',
        'dashboard.health_score': 'हेल्थ स्कोर',
        'dashboard.out_of_100': '100 में से',
        'dashboard.vitals': '👤 आपके वाइटल्स',
        'dashboard.analyze': '🔍 विश्लेषण करें',
        'dashboard.save_log': '💾 लॉग सेव करें',
        'dashboard.placeholder': 'अपने वाइटल्स भरें और हेल्थ मेट्रिक्स देखने के लिए Analyze दबाएं',
        'dashboard.breakdown': 'हेल्थ स्कोर विवरण',
        'dashboard.overall_score': 'कुल स्कोर',
        'dashboard.risk_summary': 'रिस्क सारांश',
        'dashboard.ai_advisor': '🤖 एआई हेल्थ एडवाइज़र',
        'dashboard.quick_tired': 'मैं थका क्यों महसूस कर रहा हूँ?',
        'dashboard.quick_improve': 'मेरा स्कोर कैसे बेहतर हो?',
        'dashboard.quick_weight': 'मेरा वज़न स्टेटस क्या है?',
        'dashboard.quick_tips': 'हेल्थ टिप्स',
        'dashboard.ask_health_question': 'कोई स्वास्थ्य सवाल पूछें...',
        'dashboard.history_header': '📈 हेल्थ हिस्ट्री',
        'records.vault': '🧾 मेडिकल रिकॉर्ड्स वॉल्ट',
        'records.add_title': 'बिल और प्रिस्क्रिप्शन जोड़ें',
        'records.add_copy': 'हॉस्पिटल बिल या डॉक्टर की प्रिस्क्रिप्शन अपलोड करें ताकि वे भविष्य के लिए आपके अकाउंट में सुरक्षित रहें।',
        'records.document_type': 'दस्तावेज़ प्रकार',
        'records.bill': 'बिल',
        'records.prescription': 'प्रिस्क्रिप्शन',
        'records.title': 'शीर्षक',
        'records.notes': 'नोट्स',
        'records.file': 'फ़ाइल',
        'records.save_document': 'दस्तावेज़ सेव करें',
        'records.saved_documents': 'सेव किए गए दस्तावेज़',
        'records.saved_copy': 'आपके अकाउंट में सेव हाल के बिल और प्रिस्क्रिप्शन।',
        'records.view_all': 'सभी देखें',
        'records.download': 'डाउनलोड',
        'records.empty': 'अभी कोई रिकॉर्ड सेव नहीं है। भविष्य के लिए अपना पहला बिल या प्रिस्क्रिप्शन अपलोड करें।',
        'records.saved_bills': '🧾 सेव किए गए बिल और प्रिस्क्रिप्शन',
        'records.page_title': '🧾 मेडिकल रिकॉर्ड्स',
        'records.page_subtitle': 'भविष्य की विज़िट के लिए बिल और डॉक्टर की प्रिस्क्रिप्शन सुरक्षित रूप से संग्रहीत हैं।',
        'records.page_empty': 'अभी कोई दस्तावेज़ सेव नहीं है। भविष्य के उपयोग के लिए बिल और प्रिस्क्रिप्शन जोड़ने हेतु डैशबोर्ड अपलोड सेक्शन का उपयोग करें।',
        'records.ocr_preview': 'OCR प्रीव्यू',
        'records.empty_history_prefix': 'अभी कोई बिल या प्रिस्क्रिप्शन सेव नहीं है। इन्हें अपने',
        'records.empty_history_link': 'डैशबोर्ड',
        'records.title_placeholder': 'अपोलो बिल - मार्च 2026',
        'records.notes_placeholder': 'डॉक्टर का नाम, विज़िट का कारण, भुगतान राशि, या कोई रिमाइंडर',
        'history.title': '📈 हेल्थ हिस्ट्री',
        'history.subtitle_prefix': 'आपकी पूरी वेलनेस यात्रा',
        'history.subtitle_suffix': 'कुल रिकॉर्ड',
        'history.back': '← डैशबोर्ड पर वापस',
        'history.statistics': '📊 सांख्यिकीय सारांश',
        'history.all_records': '📋 सभी रिकॉर्ड',
        'history.empty_prefix': 'अभी कोई हेल्थ हिस्ट्री नहीं है।',
        'history.empty_link': 'डैशबोर्ड पर जाएं',
        'history.empty_suffix': 'और अपना पहला लॉग सेव करें।'
    },
    ta: {
        'language.label': 'மொழி',
        'theme.dark': 'டார்க்',
        'theme.light': 'லைட்',
        'nav.home': 'முகப்பு',
        'nav.dashboard': '📊 டாஷ்போர்டு',
        'nav.history': '📈 வரலாறு',
        'nav.records': '🧾 பதிவுகள்',
        'nav.diabetes': '🩸 நீரிழிவு',
        'nav.heart': '❤️ இதயம்',
        'nav.brain': '🧠 மூளை கட்டி',
        'nav.watch': '⌚ வாட்ச்',
        'nav.chat': '💬 ஏஐ உரையாடல்',
        'auth.login': 'உள்நுழை',
        'auth.register': 'பதிவு செய்',
        'auth.logout': 'வெளியேறு',
        'auth.tagline': 'உங்கள் டிஜிட்டல் ஹெல்த் ட்வின்',
        'footer.disclaimer': '⚕️ HealthTwin v2.0 - ஏஐ அடிப்படையிலான ஆரோக்கிய கணிப்புகள் கல்வி நோக்கத்திற்காக மட்டுமே. எப்போதும் மருத்துவரை அணுகவும்.',
        'home.badge': 'துல்லியமான ஆரோக்கிய நுண்ணறிவு',
        'home.title': 'உங்கள் ஹெல்த் ட்வினுக்கான ஏஐ அடுக்கை அறிந்து கொள்ளுங்கள்.',
        'home.subtitle': 'HealthTwin முன்கணிப்பு கருவிகள், தினசரி வைட்டல் கண்காணிப்பு, மற்றும் எப்போதும் அணுகக்கூடிய மருத்துவ உதவியாளரை ஒரே அமைதியான இடத்தில் தருகிறது.',
        'home.open_dashboard': 'டாஷ்போர்டை திற',
        'home.talk_ai': 'ஏஐயுடன் பேசு',
        'home.review_history': 'வரலாற்றைப் பார்',
        'home.create_account': 'இலவச கணக்கு உருவாக்கு',
        'home.sign_in': 'உள்நுழை',
        'home.stat_models_title': '3 முக்கிய மாதிரிகள்',
        'home.stat_models_copy': 'நீரிழிவு, இதயம் மற்றும் எம்ஆர்ஐ ஆதரவு',
        'home.stat_cockpit_title': '1 ஒருங்கிணைந்த கட்டுப்பாட்டு மையம்',
        'home.stat_cockpit_copy': 'முன்கணிப்புகள், வாட்ச் தரவு மற்றும் வரலாறு',
        'home.stat_ai_title': '24/7 ஏஐ வழிகாட்டல்',
        'home.stat_ai_copy': 'கேள்விகள், விளக்கங்கள் மற்றும் அடுத்த படிகள்',
        'home.snapshot_kicker': 'நேரடி நலநிலை படம்',
        'home.health_score_small': 'ஹெல்த் ஸ்கோர்',
        'home.recovery_trend': 'மீட்பு போக்கு',
        'home.recovery_value': 'நிலையாக',
        'home.sleep_consistency': 'தூக்க ஒற்றுமை',
        'home.heart_load': 'இதய சுமை',
        'home.heart_load_value': 'கவனமாக பார்க்கவும்',
        'home.covers_kicker': 'HealthTwin உள்ளடக்கம்',
        'home.cover_predictions_title': 'முன்கணிப்புகள்',
        'home.cover_predictions_copy': 'முக்கிய நோய் ஆபத்து சோதனைகளுக்கான எம்எல் ஆதரவு',
        'home.cover_assistant_title': 'உதவியாளர்',
        'home.cover_assistant_copy': 'ரிட்ரீவல் ஆதரவு கொண்ட மருத்துவ கேள்வி-பதில்கள்',
        'home.cover_tracking_title': 'கண்காணிப்பு',
        'home.cover_tracking_copy': 'வைட்டல்ஸ், பதிவுகள், வரைபடங்கள் மற்றும் வியரபிள் சிமுலேஷன்',
        'home.cover_history_title': 'வரலாறு',
        'home.cover_history_copy': 'காலப்போக்கில் போக்குகளைப் பார்த்து மாற்றங்களை கண்டறியுங்கள்',
        'home.stat_pipeline': 'நோய் முன்கணிப்பு பைப்லைன்கள்',
        'home.stat_assistant': 'சூழல் சார்ந்த மருத்துவ உதவியாளர்',
        'home.stat_view': 'பதிவுகள், வைட்டல்ஸ் மற்றும் சிமுலேட்டட் வியரபிள்களின் பார்வை',
        'home.stat_fast': 'பகுப்பாய்வு செய்து, சேமித்து, உங்கள் ஆரோக்கிய ஸ்னாப்ஷாட்களை மீண்டும் பாருங்கள்',
        'home.modules_kicker': 'பிளாட்ஃபாரம் கூறுகள்',
        'home.modules_title': 'முக்கியமான அனைத்தும், ஒரு திரை தூரத்தில்.',
        'home.modules_copy': 'ஒவ்வொரு கருவியும் நடைமுறை சுகாதார பணிச்சூழலுக்காக வடிவமைக்கப்பட்டுள்ளது: அளவிடு, மதிப்பிடு, புரிந்து கொள், கண்காணி.',
        'home.card_dashboard_title': 'ஹெல்த் டாஷ்போர்டு',
        'home.card_dashboard_copy': 'உங்கள் ஹெல்த் ஸ்கோரை கணக்கிட்டு, முக்கிய வைட்டல்களை கண்காணித்து, அபாயச் சுட்டிகளை காணவும் மற்றும் அதே பணிச்சூழலில் ஏஐ ஆலோசனையைப் பெறவும்.',
        'home.card_history_title': 'ஹெல்த் வரலாறு',
        'home.card_history_copy': 'மீட்பு, பழக்கவழக்கம் மற்றும் ஒற்றுமையை காட்டும் வரைபடங்களுடன் காலப்போக்கில் சேமித்த பதிவுகளைப் பாருங்கள்.',
        'home.card_diabetes_title': 'நீரிழிவு அபாயம்',
        'home.card_diabetes_copy': 'குளுகோஸ், பிஎம்ஐ, வயது மற்றும் தொடர்புடைய காரணிகளின் அடிப்படையில் நீரிழிவின் வாய்ப்பை மதிப்பிடுங்கள்.',
        'home.card_heart_title': 'இதய நோய் கண்டறிதல்',
        'home.card_heart_copy': 'இரத்த அழுத்தம், கொலஸ்ட்ரால், ஈசிஜி சார்ந்த சிக்னல்கள் மற்றும் பிற வைட்டல்களின் மூலம் இதய அபாயத்தை மதிப்பிடுங்கள்.',
        'home.card_brain_title': 'மூளை எம்ஆர்ஐ வகைப்பாடு',
        'home.card_brain_copy': 'படவழி டீப் லெர்னிங் உதவியால் முக்கிய மூளை கட்டி வகைகளாக எம்ஆர்ஐ ஸ்கேன்களை வகைப்படுத்துங்கள்.',
        'home.card_watch_title': 'ஸ்மார்ட் வாட்ச் சிமுலேஷன்',
        'home.card_watch_copy': 'கூட்டு வியரபிள் பாணி டாஷ்போர்டின் மூலம் இதய துடிப்பு, ஆக்சிஜன், மனஅழுத்தம் மற்றும் செயற்பாட்டு தரவுகளை ஆய்வு செய்யுங்கள்.',
        'home.card_ai_title': 'ஏஐ மருத்துவ உதவியாளர்',
        'home.card_ai_copy': 'வழிகாட்டலும் தெளிவும் தரும் மையப்படுத்தப்பட்ட இடைமுகத்தில் அறிகுறிகள், சிகிச்சை, மீட்பு மற்றும் நலனைக் குறித்து கேளுங்கள்.',
        'login.title': 'மீண்டும் வரவேற்கிறோம்',
        'login.subtitle': 'உங்கள் ஹெல்த் டாஷ்போர்டை அணுக உள்நுழைக',
        'login.remember': 'என்னை நினைவில் கொள்',
        'login.submit': 'உள்நுழை →',
        'login.switch_prefix': 'கணக்கு இல்லையா?',
        'login.switch_link': 'ஒன்றை உருவாக்கு',
        'register.title': 'கணக்கு உருவாக்கு',
        'register.subtitle': 'உங்கள் ஆரோக்கிய பயணத்தை கண்காணிக்க தொடங்குங்கள்',
        'register.confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        'register.submit': 'கணக்கு உருவாக்கு →',
        'register.switch_prefix': 'ஏற்கனவே கணக்கு உள்ளதா?',
        'register.switch_link': 'உள்நுழை',
        'form.username': 'பயனர் பெயர்',
        'form.email': 'மின்னஞ்சல்',
        'form.password': 'கடவுச்சொல்',
        'form.gender': 'பால்',
        'form.age': 'வயது',
        'form.weight': 'எடை (கிலோ)',
        'form.height': 'உயரம் (செ.மீ)',
        'form.steps': 'தினசரி அடிகள்',
        'form.sleep': 'தூக்கம் (மணி)',
        'form.water': 'தண்ணீர் (லிட்டர்)',
        'form.heart_rate': 'இதய துடிப்பு (bpm)',
        'placeholder.username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
        'placeholder.choose_username': 'பயனர் பெயரைத் தேர்வுசெய்க',
        'placeholder.password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
        'placeholder.password_min': 'குறைந்தது 6 எழுத்துகள்',
        'placeholder.repeat_password': 'கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
        'placeholder.email': 'your@email.com',
        'dashboard.title': '📊 ஹெல்த் டாஷ்போர்டு',
        'dashboard.welcome': 'மீண்டும் வரவேற்கிறோம்,',
        'dashboard.health_score': 'ஹெல்த் ஸ்கோர்',
        'dashboard.out_of_100': '100 இல்',
        'dashboard.vitals': '👤 உங்கள் வைட்டல்ஸ்',
        'dashboard.analyze': '🔍 பகுப்பாய்வு செய்',
        'dashboard.save_log': '💾 பதிவை சேமி',
        'dashboard.placeholder': 'உங்கள் வைட்டல்களை உள்ளிட்டு Analyze அழுத்தி உங்கள் ஆரோக்கிய அளவுகளைப் பாருங்கள்',
        'dashboard.breakdown': 'ஹெல்த் ஸ்கோர் பிரிப்பு',
        'dashboard.overall_score': 'மொத்த ஸ்கோர்',
        'dashboard.risk_summary': 'ஆபத்து சுருக்கம்',
        'dashboard.ai_advisor': '🤖 ஏஐ ஹெல்த் ஆலோசகர்',
        'dashboard.quick_tired': 'நான் ஏன் சோர்வாக உள்ளேன்?',
        'dashboard.quick_improve': 'என் ஸ்கோரை எப்படி மேம்படுத்தலாம்?',
        'dashboard.quick_weight': 'என் எடை நிலை என்ன?',
        'dashboard.quick_tips': 'ஆரோக்கிய குறிப்புகள்',
        'dashboard.ask_health_question': 'ஒரு சுகாதார கேள்வி கேளுங்கள்...',
        'dashboard.history_header': '📈 ஹெல்த் வரலாறு',
        'records.vault': '🧾 மருத்துவ பதிவுகள் வால்ட்',
        'records.add_title': 'பில் மற்றும் பிரிஸ்கிரிப்ஷன் சேர்க்கவும்',
        'records.add_copy': 'மருத்துவமனை பில்கள் அல்லது மருத்துவர் பரிந்துரைகளை பதிவேற்றம் செய்து எதிர்கால பயன்பாட்டுக்காக உங்கள் கணக்கில் வைத்திருங்கள்.',
        'records.document_type': 'ஆவண வகை',
        'records.bill': 'பில்',
        'records.prescription': 'பிரிஸ்கிரிப்ஷன்',
        'records.title': 'தலைப்பு',
        'records.notes': 'குறிப்புகள்',
        'records.file': 'கோப்பு',
        'records.save_document': 'ஆவணத்தை சேமி',
        'records.saved_documents': 'சேமிக்கப்பட்ட ஆவணங்கள்',
        'records.saved_copy': 'உங்கள் கணக்கில் சேமிக்கப்பட்ட சமீபத்திய பில்கள் மற்றும் பரிந்துரைகள்.',
        'records.view_all': 'அனைத்தையும் பார்',
        'records.download': 'பதிவிறக்கு',
        'records.empty': 'இன்னும் பதிவுகள் இல்லை. எதிர்காலத்திற்காக உங்கள் முதல் பில் அல்லது பிரிஸ்கிரிப்ஷனை பதிவேற்றவும்.',
        'records.saved_bills': '🧾 சேமிக்கப்பட்ட பில்கள் மற்றும் பிரிஸ்கிரிப்ஷன்கள்',
        'records.page_title': '🧾 மருத்துவ பதிவுகள்',
        'records.page_subtitle': 'பில்கள் மற்றும் மருத்துவர் பரிந்துரைகள் எதிர்கால வருகைகளுக்காக பாதுகாப்பாக சேமிக்கப்பட்டுள்ளன.',
        'records.page_empty': 'இன்னும் ஆவணங்கள் சேமிக்கப்படவில்லை. டாஷ்போர்டில் உள்ள அப்லோடு பகுதியைப் பயன்படுத்தி பில்கள் மற்றும் பிரிஸ்கிரிப்ஷன்களைச் சேர்க்கவும்.',
        'records.ocr_preview': 'OCR முன்னோட்டம்',
        'records.empty_history_prefix': 'இன்னும் பில்கள் அல்லது பிரிஸ்கிரிப்ஷன்கள் சேமிக்கப்படவில்லை. அவற்றை உங்கள்',
        'records.empty_history_link': 'டாஷ்போர்டில்',
        'records.title_placeholder': 'அப்பல்லோ பில் - மார்ச் 2026',
        'records.notes_placeholder': 'மருத்துவர் பெயர், வருகை காரணம், செலுத்திய தொகை, அல்லது நினைவூட்டல்',
        'history.title': '📈 ஆரோக்கிய வரலாறு',
        'history.subtitle_prefix': 'உங்கள் முழு நலப் பயணம்',
        'history.subtitle_suffix': 'மொத்த பதிவுகள்',
        'history.back': '← டாஷ்போர்டுக்குத் திரும்பு',
        'history.statistics': '📊 புள்ளிவிவர சுருக்கம்',
        'history.all_records': '📋 அனைத்து பதிவுகளும்',
        'history.empty_prefix': 'இன்னும் ஆரோக்கிய வரலாறு இல்லை.',
        'history.empty_link': 'டாஷ்போர்டுக்குச் செல்லவும்',
        'history.empty_suffix': 'மற்றும் உங்கள் முதல் பதிவைச் சேமிக்கவும்.'
    }
};

// Auto-dismiss flash messages after 5 seconds
document.addEventListener('DOMContentLoaded', () => {
    const root = document.documentElement;
    const themeToggle = document.getElementById('themeToggle');
    const themeToggleIcon = document.getElementById('themeToggleIcon');
    const themeToggleText = document.getElementById('themeToggleText');
    const languageSelect = document.getElementById('languageSelect');

    const translate = (language) => {
        const locale = HEALTH_TWIN_TRANSLATIONS[language] ? language : 'en';
        const messages = HEALTH_TWIN_TRANSLATIONS[locale];
        document.documentElement.lang = locale;

        document.querySelectorAll('[data-i18n]').forEach((element) => {
            const key = element.getAttribute('data-i18n');
            if (messages[key]) {
                element.textContent = messages[key];
            }
        });

        document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
            const key = element.getAttribute('data-i18n-placeholder');
            if (messages[key]) {
                element.setAttribute('placeholder', messages[key]);
            }
        });
    };

    const syncThemeToggle = () => {
        const darkMode = root.classList.contains('dark-theme');
        if (themeToggleIcon) themeToggleIcon.textContent = darkMode ? '☀' : '☾';
        const lang = localStorage.getItem('healthtwin-language') || 'en';
        if (themeToggleText) {
            themeToggleText.textContent = darkMode
                ? HEALTH_TWIN_TRANSLATIONS[lang]?.['theme.light'] || 'Light'
                : HEALTH_TWIN_TRANSLATIONS[lang]?.['theme.dark'] || 'Dark';
        }
        if (themeToggle) themeToggle.setAttribute('aria-label', darkMode ? 'Switch to light mode' : 'Switch to dark mode');
    };

    const savedLanguage = localStorage.getItem('healthtwin-language') || 'en';
    if (languageSelect) {
        languageSelect.value = savedLanguage;
        languageSelect.addEventListener('change', () => {
            localStorage.setItem('healthtwin-language', languageSelect.value);
            translate(languageSelect.value);
            syncThemeToggle();
        });
    }

    translate(savedLanguage);

    if (themeToggle) {
        syncThemeToggle();
        themeToggle.addEventListener('click', () => {
            root.classList.toggle('dark-theme');
            localStorage.setItem('healthtwin-theme', root.classList.contains('dark-theme') ? 'dark' : 'light');
            syncThemeToggle();
        });
    }

    document.querySelectorAll('.flash').forEach(el => {
        setTimeout(() => {
            el.style.opacity = '0';
            el.style.transform = 'translateX(120%)';
            el.style.transition = 'all 0.4s';
            setTimeout(() => el.remove(), 400);
        }, 5000);
    });
});
